/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 */
import {
  z as zod
} from 'zod';

/**
 * ## 实验性 API， 本 schema 和实际的 API 行为都可能随时发生改动

目前支持的筛选条件包括:
- `type`: 条目类型，参照 `SubjectType` enum， `或`。
- `tag`: 标签，可以多次出现。`且` 关系。
- `air_date`: 播出日期/发售日期。`且` 关系。
- `rating`: 用于搜索指定评分的条目。`且` 关系。
- `rank`: 用于搜索指定排名的条目。`且` 关系。
- `nsfw`: 使用 `include` 包含NSFW搜索结果。默认排除搜索NSFW条目。无权限情况下忽略此选项，不会返回NSFW条目。

不同筛选条件之间为 `且`

 * @summary 条目搜索
 */
export const searchSubjectsQueryParams = zod.object({
  "limit": zod.number().optional().describe('分页参数'),
  "offset": zod.number().optional().describe('分页参数')
})

export const searchSubjectsBodySortDefault = "match";

export const searchSubjectsBody = zod.object({
  "keyword": zod.string(),
  "sort": zod.enum(['match', 'heat', 'rank', 'score']).default(searchSubjectsBodySortDefault).describe('排序规则\n\n- `match` meilisearch 的默认排序，按照匹配程度\n- `heat` 收藏人数\n- `rank` 排名由高到低\n- `score` 评分\n'),
  "filter": zod.object({
  "type": zod.array(zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`')).optional().describe('条目类型，参照 `SubjectType` enum，多值之间为 `或` 的关系。'),
  "meta_tags": zod.array(zod.string()).optional().describe('公共标签。多个值之间为 `且` 关系。可以用 `-` 排除标签。比如 `-科幻` 可以排除科幻标签。'),
  "tag": zod.array(zod.string()).optional().describe('标签，可以多次出现。多值之间为 `且` 关系。'),
  "air_date": zod.array(zod.string()).optional().describe('播出日期/发售日期，日期必需为 `YYYY-MM-DD` 格式。多值之间为 `且` 关系。'),
  "rating": zod.array(zod.string()).optional().describe('用于搜索指定评分的条目，多值之间为 `且` 关系。'),
  "rank": zod.array(zod.string()).optional().describe('用于搜索指定排名的条目，多值之间为 `且` 关系。'),
  "nsfw": zod.boolean().optional().describe('无权限的用户会直接忽略此字段，不会返回R18条目。\n\n默认或者 `null` 会返回包含 R18 的所有搜索结果。\n\n`true` 只会返回 R18 条目。\n\n`false` 只会返回非 R18 条目。\n')
}).optional().describe('不同条件之间是 `且` 的关系')
})

export const searchSubjectsResponseTotalDefault = 0;export const searchSubjectsResponseLimitDefault = 0;export const searchSubjectsResponseOffsetDefault = 0;export const searchSubjectsResponseDataDefault = [];

export const searchSubjectsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "summary": zod.string(),
  "series": zod.boolean().describe('是否为书籍系列的主条目'),
  "nsfw": zod.boolean(),
  "locked": zod.boolean(),
  "date": zod.string().optional().describe('air date in `YYYY-MM-DD` format'),
  "platform": zod.string().describe('TV, Web, 欧美剧, DLC...'),
  "images": zod.object({
  "large": zod.string(),
  "common": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}),
  "infobox": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.union([zod.string(),zod.array(zod.union([zod.object({
  "k": zod.string(),
  "v": zod.string()
}),zod.object({
  "v": zod.string()
})]))])
})).optional(),
  "volumes": zod.number().describe('书籍条目的册数，由旧服务端从wiki中解析'),
  "eps": zod.number().describe('由旧服务端从wiki中解析，对于书籍条目为`话数`'),
  "total_episodes": zod.number().describe('数据库中的章节数量'),
  "rating": zod.object({
  "rank": zod.number(),
  "total": zod.number(),
  "count": zod.object({
  "1": zod.number().optional(),
  "2": zod.number().optional(),
  "3": zod.number().optional(),
  "4": zod.number().optional(),
  "5": zod.number().optional(),
  "6": zod.number().optional(),
  "7": zod.number().optional(),
  "8": zod.number().optional(),
  "9": zod.number().optional(),
  "10": zod.number().optional()
}),
  "score": zod.number()
}),
  "collection": zod.object({
  "wish": zod.number(),
  "collect": zod.number(),
  "doing": zod.number(),
  "on_hold": zod.number(),
  "dropped": zod.number()
}),
  "meta_tags": zod.array(zod.string()).describe('由维基人维护的 tag'),
  "tags": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
}))
})).default(searchSubjectsResponseDataDefault)
})


/**
 * ## 实验性 API， 本 schema 和实际的 API 行为都可能随时发生改动

目前支持的筛选条件包括:
- `nsfw`: 使用 `include` 包含NSFW搜索结果。默认排除搜索NSFW条目。无权限情况下忽略此选项，不会返回NSFW条目。

 * @summary 角色搜索
 */
export const searchCharactersQueryParams = zod.object({
  "limit": zod.number().optional().describe('分页参数'),
  "offset": zod.number().optional().describe('分页参数')
})

export const searchCharactersBody = zod.object({
  "keyword": zod.string(),
  "filter": zod.object({
  "nsfw": zod.boolean().optional().describe('无权限的用户会直接忽略此字段，不会返回 R18 角色。\n\n默认或者 `null` 会返回包含 R18 的所有搜索结果。\n\n`true` 只会返回 R18 角色。\n\n`false` 只会返回非 R18 角色。\n')
}).optional().describe('不同条件之间是 `且` 的关系')
})

export const searchCharactersResponseTotalDefault = 0;export const searchCharactersResponseLimitDefault = 0;export const searchCharactersResponseOffsetDefault = 0;export const searchCharactersResponseDataDefault = [];

export const searchCharactersResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('type of a character 角色，机体，舰船，组织...').describe('角色，机体，舰船，组织...'),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "summary": zod.string(),
  "locked": zod.boolean(),
  "infobox": zod.array(zod.object({

})).optional().describe('server parsed infobox, a map from key to string or tuple\nnull if server infobox is not valid'),
  "gender": zod.string().optional().describe('parsed from wiki, maybe null'),
  "blood_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('Blood type of a person. A, B, AB, O').optional().describe('parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`'),
  "birth_year": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "birth_mon": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "birth_day": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "stat": zod.object({
  "comments": zod.number(),
  "collects": zod.number()
})
})).default(searchCharactersResponseDataDefault)
})


/**
 * ## 实验性 API， 本 schema 和实际的 API 行为都可能随时发生改动

目前支持的筛选条件包括:
- `career`: 职业，可以多次出现。`且` 关系。

不同筛选条件之间为 `且`

 * @summary 人物搜索
 */
export const searchPersonsQueryParams = zod.object({
  "limit": zod.number().optional().describe('分页参数'),
  "offset": zod.number().optional().describe('分页参数')
})

export const searchPersonsBody = zod.object({
  "keyword": zod.string(),
  "filter": zod.object({
  "career": zod.array(zod.string()).optional().describe('职业，可以多次出现。多值之间为 `且` 关系。')
}).optional().describe('不同条件之间是 `且` 的关系')
})

export const searchPersonsResponseTotalDefault = 0;export const searchPersonsResponseLimitDefault = 0;export const searchPersonsResponseOffsetDefault = 0;export const searchPersonsResponseDataDefault = [];

export const searchPersonsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`').describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`'),
  "career": zod.array(zod.enum(['producer', 'mangaka', 'artist', 'seiyu', 'writer', 'illustrator', 'actor']).describe('An enumeration.')),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "short_summary": zod.string(),
  "locked": zod.boolean()
})).default(searchPersonsResponseDataDefault)
})


/**
 * 第一页会 cache 24h，之后会 cache 1h
 * @summary 浏览条目
 */
export const getSubjectsQueryLimitDefault = 30;
export const getSubjectsQueryLimitMax = 50;
export const getSubjectsQueryOffsetDefault = 0;
export const getSubjectsQueryOffsetMin = 0;


export const getSubjectsQueryParams = zod.object({
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型'),
  "cat": zod.union([zod.union([zod.literal(0),zod.literal(1001),zod.literal(1002),zod.literal(1003)]).describe('书籍类型\n- `0` 为 其他\n- `1001` 为 漫画\n- `1002` 为 小说\n- `1003` 为 画集'),zod.union([zod.literal(0),zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(5)]).describe('动画类型\n- `0` 为 其他\n- `1` 为 TV\n- `2` 为 OVA\n- `3` 为 Movie\n- `5` 为 WEB'),zod.union([zod.literal(0),zod.literal(4001),zod.literal(4003),zod.literal(4002),zod.literal(4005)]).describe('游戏类型\n- `0` 为 其他\n- `4001` 为 游戏\n- `4002` 为 软件\n- `4003` 为 扩展包\n- `4005` 为 桌游'),zod.union([zod.literal(0),zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(6001),zod.literal(6002),zod.literal(6003),zod.literal(6004)]).describe('电影类型\n- `0` 为 其他\n- `1` 为 日剧\n- `2` 为 欧美剧\n- `3` 为 华语剧\n- `6001` 为 电视剧\n- `6002` 为 电影\n- `6003` 为 演出\n- `6004` 为 综艺')]).optional().describe('条目分类，参照 `SubjectCategory` enum'),
  "series": zod.boolean().optional().describe('是否系列，仅对书籍类型的条目有效'),
  "platform": zod.string().optional().describe('平台，仅对游戏类型的条目有效'),
  "sort": zod.string().optional().describe('排序，枚举值 {date|rank}'),
  "year": zod.number().optional().describe('年份'),
  "month": zod.number().optional().describe('月份'),
  "limit": zod.number().min(1).max(getSubjectsQueryLimitMax).default(getSubjectsQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getSubjectsQueryOffsetMin).optional().describe('分页参数')
})

export const getSubjectsResponseTotalDefault = 0;export const getSubjectsResponseLimitDefault = 0;export const getSubjectsResponseOffsetDefault = 0;export const getSubjectsResponseDataDefault = [];

export const getSubjectsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "summary": zod.string(),
  "series": zod.boolean().describe('是否为书籍系列的主条目'),
  "nsfw": zod.boolean(),
  "locked": zod.boolean(),
  "date": zod.string().optional().describe('air date in `YYYY-MM-DD` format'),
  "platform": zod.string().describe('TV, Web, 欧美剧, DLC...'),
  "images": zod.object({
  "large": zod.string(),
  "common": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}),
  "infobox": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.union([zod.string(),zod.array(zod.union([zod.object({
  "k": zod.string(),
  "v": zod.string()
}),zod.object({
  "v": zod.string()
})]))])
})).optional(),
  "volumes": zod.number().describe('书籍条目的册数，由旧服务端从wiki中解析'),
  "eps": zod.number().describe('由旧服务端从wiki中解析，对于书籍条目为`话数`'),
  "total_episodes": zod.number().describe('数据库中的章节数量'),
  "rating": zod.object({
  "rank": zod.number(),
  "total": zod.number(),
  "count": zod.object({
  "1": zod.number().optional(),
  "2": zod.number().optional(),
  "3": zod.number().optional(),
  "4": zod.number().optional(),
  "5": zod.number().optional(),
  "6": zod.number().optional(),
  "7": zod.number().optional(),
  "8": zod.number().optional(),
  "9": zod.number().optional(),
  "10": zod.number().optional()
}),
  "score": zod.number()
}),
  "collection": zod.object({
  "wish": zod.number(),
  "collect": zod.number(),
  "doing": zod.number(),
  "on_hold": zod.number(),
  "dropped": zod.number()
}),
  "meta_tags": zod.array(zod.string()).describe('由维基人维护的 tag'),
  "tags": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
}))
})).default(getSubjectsResponseDataDefault)
})


/**
 * cache with 300s
 * @summary 获取条目
 */
export const getSubjectByIdParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const getSubjectByIdResponse = zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "summary": zod.string(),
  "series": zod.boolean().describe('是否为书籍系列的主条目'),
  "nsfw": zod.boolean(),
  "locked": zod.boolean(),
  "date": zod.string().optional().describe('air date in `YYYY-MM-DD` format'),
  "platform": zod.string().describe('TV, Web, 欧美剧, DLC...'),
  "images": zod.object({
  "large": zod.string(),
  "common": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}),
  "infobox": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.union([zod.string(),zod.array(zod.union([zod.object({
  "k": zod.string(),
  "v": zod.string()
}),zod.object({
  "v": zod.string()
})]))])
})).optional(),
  "volumes": zod.number().describe('书籍条目的册数，由旧服务端从wiki中解析'),
  "eps": zod.number().describe('由旧服务端从wiki中解析，对于书籍条目为`话数`'),
  "total_episodes": zod.number().describe('数据库中的章节数量'),
  "rating": zod.object({
  "rank": zod.number(),
  "total": zod.number(),
  "count": zod.object({
  "1": zod.number().optional(),
  "2": zod.number().optional(),
  "3": zod.number().optional(),
  "4": zod.number().optional(),
  "5": zod.number().optional(),
  "6": zod.number().optional(),
  "7": zod.number().optional(),
  "8": zod.number().optional(),
  "9": zod.number().optional(),
  "10": zod.number().optional()
}),
  "score": zod.number()
}),
  "collection": zod.object({
  "wish": zod.number(),
  "collect": zod.number(),
  "doing": zod.number(),
  "on_hold": zod.number(),
  "dropped": zod.number()
}),
  "meta_tags": zod.array(zod.string()).describe('由维基人维护的 tag'),
  "tags": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
}))
})


/**
 * @summary Get Subject Image
 */
export const getSubjectImageByIdParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const getSubjectImageByIdQueryParams = zod.object({
  "type": zod.string().describe('枚举值 {small|grid|large|medium|common}')
})


/**
 * @summary Get Subject Persons
 */
export const getRelatedPersonsBySubjectIdParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const getRelatedPersonsBySubjectIdResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`').describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`'),
  "career": zod.array(zod.enum(['producer', 'mangaka', 'artist', 'seiyu', 'writer', 'illustrator', 'actor']).describe('An enumeration.')),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "relation": zod.string(),
  "eps": zod.string().describe('参与章节/曲目')
})
export const getRelatedPersonsBySubjectIdResponse = zod.array(getRelatedPersonsBySubjectIdResponseItem)


/**
 * @summary Get Subject Characters
 */
export const getRelatedCharactersBySubjectIdParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const getRelatedCharactersBySubjectIdResponseActorsDefault = [];

export const getRelatedCharactersBySubjectIdResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('type of a character 角色，机体，舰船，组织...').describe('角色，机体，舰船，组织...'),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "relation": zod.string(),
  "actors": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`').describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`'),
  "career": zod.array(zod.enum(['producer', 'mangaka', 'artist', 'seiyu', 'writer', 'illustrator', 'actor']).describe('An enumeration.')),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "short_summary": zod.string(),
  "locked": zod.boolean()
})).default(getRelatedCharactersBySubjectIdResponseActorsDefault).describe('演员列表')
})
export const getRelatedCharactersBySubjectIdResponse = zod.array(getRelatedCharactersBySubjectIdResponseItem)


/**
 * @summary Get Subject Relations
 */
export const getRelatedSubjectsBySubjectIdParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const getRelatedSubjectsBySubjectIdResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "name": zod.string(),
  "name_cn": zod.string(),
  "images": zod.object({
  "large": zod.string(),
  "common": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional(),
  "relation": zod.string()
})
export const getRelatedSubjectsBySubjectIdResponse = zod.array(getRelatedSubjectsBySubjectIdResponseItem)


/**
 * @summary Get Episodes
 */
export const getEpisodesQueryLimitDefault = 100;
export const getEpisodesQueryLimitMax = 200;
export const getEpisodesQueryOffsetDefault = 0;
export const getEpisodesQueryOffsetMin = 0;


export const getEpisodesQueryParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID'),
  "type": zod.union([zod.literal(0),zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5),zod.literal(6)]).describe('本篇 = 0\n特别篇 = 1\nOP = 2\nED = 3\n预告/宣传/广告 = 4\nMAD = 5\n其他 = 6').optional().describe('参照章节的`type`'),
  "limit": zod.number().min(1).max(getEpisodesQueryLimitMax).default(getEpisodesQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getEpisodesQueryOffsetMin).optional().describe('分页参数')
})

export const getEpisodesResponseTotalDefault = 0;export const getEpisodesResponseLimitDefault = 0;export const getEpisodesResponseOffsetDefault = 0;export const getEpisodesResponseDataDefault = [];

export const getEpisodesResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.number().describe('`0` 本篇，`1` SP，`2` OP，`3` ED'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "sort": zod.number().describe('同类条目的排序和集数'),
  "ep": zod.number().optional().describe('条目内的集数, 从`1`开始。非本篇剧集的此字段无意义'),
  "airdate": zod.string(),
  "comment": zod.number(),
  "duration": zod.string().describe('维基人填写的原始时长'),
  "desc": zod.string().describe('简介'),
  "disc": zod.number().describe('音乐曲目的碟片数'),
  "duration_seconds": zod.number().optional().describe('服务器解析的时长，无法解析时为 `0`')
})).default(getEpisodesResponseDataDefault)
})


/**
 * @summary Get Episode
 */
export const getEpisodeByIdParams = zod.object({
  "episode_id": zod.number().min(1).describe('章节 ID')
})

export const getEpisodeByIdResponse = zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(0),zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5),zod.literal(6)]).describe('本篇 = 0\n特别篇 = 1\nOP = 2\nED = 3\n预告/宣传/广告 = 4\nMAD = 5\n其他 = 6'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "sort": zod.number().describe('同类条目的排序和集数'),
  "ep": zod.number().optional().describe('条目内的集数, 从`1`开始。非本篇剧集的此字段无意义'),
  "airdate": zod.string(),
  "comment": zod.number(),
  "duration": zod.string(),
  "desc": zod.string().describe('简介'),
  "disc": zod.number().describe('音乐曲目的碟片数'),
  "subject_id": zod.number()
})


/**
 * cache with 60s
 * @summary Get Character Detail
 */
export const getCharacterByIdParams = zod.object({
  "character_id": zod.number().min(1).describe('角色 ID')
})

export const getCharacterByIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('type of a character 角色，机体，舰船，组织...').describe('角色，机体，舰船，组织...'),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "summary": zod.string(),
  "locked": zod.boolean(),
  "infobox": zod.array(zod.object({

})).optional().describe('server parsed infobox, a map from key to string or tuple\nnull if server infobox is not valid'),
  "gender": zod.string().optional().describe('parsed from wiki, maybe null'),
  "blood_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('Blood type of a person. A, B, AB, O').optional().describe('parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`'),
  "birth_year": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "birth_mon": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "birth_day": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "stat": zod.object({
  "comments": zod.number(),
  "collects": zod.number()
})
})


/**
 * @summary Get Character Image
 */
export const getCharacterImageByIdParams = zod.object({
  "character_id": zod.number().min(1).describe('角色 ID')
})

export const getCharacterImageByIdQueryParams = zod.object({
  "type": zod.string().describe('枚举值 {small|grid|large|medium}')
})


/**
 * @summary get character related subjects
 */
export const getRelatedSubjectsByCharacterIdParams = zod.object({
  "character_id": zod.number().min(1).describe('角色 ID')
})

export const getRelatedSubjectsByCharacterIdResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "staff": zod.string(),
  "name": zod.string(),
  "name_cn": zod.string(),
  "image": zod.string().optional()
})
export const getRelatedSubjectsByCharacterIdResponse = zod.array(getRelatedSubjectsByCharacterIdResponseItem)


/**
 * @summary get character related persons
 */
export const getRelatedPersonsByCharacterIdParams = zod.object({
  "character_id": zod.number().min(1).describe('角色 ID')
})

export const getRelatedPersonsByCharacterIdResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('type of a character 角色，机体，舰船，组织...').describe('角色，机体，舰船，组织...'),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "subject_id": zod.number(),
  "subject_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "subject_name": zod.string(),
  "subject_name_cn": zod.string(),
  "staff": zod.string().optional()
})
export const getRelatedPersonsByCharacterIdResponse = zod.array(getRelatedPersonsByCharacterIdResponseItem)


/**
 * 为当前用户收藏角色
 * @summary Collect character for current user
 */
export const collectCharacterByCharacterIdAndUserIdParams = zod.object({
  "character_id": zod.number().min(1).describe('角色 ID')
})


/**
 * 为当前用户取消收藏角色
 * @summary Uncollect character for current user
 */
export const uncollectCharacterByCharacterIdAndUserIdParams = zod.object({
  "character_id": zod.number().min(1).describe('角色 ID')
})


/**
 * cache with 60s
 * @summary Get Person
 */
export const getPersonByIdParams = zod.object({
  "person_id": zod.number().min(1).describe('人物 ID')
})

export const getPersonByIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`').describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`'),
  "career": zod.array(zod.enum(['producer', 'mangaka', 'artist', 'seiyu', 'writer', 'illustrator', 'actor']).describe('An enumeration.')),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "summary": zod.string(),
  "locked": zod.boolean(),
  "last_modified": zod.string().datetime({}).describe('currently it\'s latest user comment time, it will be replaced by wiki modified date in the future'),
  "infobox": zod.array(zod.object({

})).optional().describe('server parsed infobox, a map from key to string or tuple\nnull if server infobox is not valid'),
  "gender": zod.string().optional().describe('parsed from wiki, maybe null'),
  "blood_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('Blood type of a person. A, B, AB, O').optional().describe('parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`'),
  "birth_year": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "birth_mon": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "birth_day": zod.number().optional().describe('parsed from wiki, maybe `null`'),
  "stat": zod.object({
  "comments": zod.number(),
  "collects": zod.number()
})
})


/**
 * @summary Get Person Image
 */
export const getPersonImageByIdParams = zod.object({
  "person_id": zod.number().min(1).describe('人物 ID')
})

export const getPersonImageByIdQueryParams = zod.object({
  "type": zod.string().describe('枚举值 {small|grid|large|medium}')
})


/**
 * @summary get person related subjects
 */
export const getRelatedSubjectsByPersonIdParams = zod.object({
  "person_id": zod.number().min(1).describe('人物 ID')
})

export const getRelatedSubjectsByPersonIdResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "staff": zod.string(),
  "name": zod.string(),
  "name_cn": zod.string(),
  "image": zod.string().optional()
})
export const getRelatedSubjectsByPersonIdResponse = zod.array(getRelatedSubjectsByPersonIdResponseItem)


/**
 * @summary get person related characters
 */
export const getRelatedCharactersByPersonIdParams = zod.object({
  "person_id": zod.number().min(1).describe('人物 ID')
})

export const getRelatedCharactersByPersonIdResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('type of a character 角色，机体，舰船，组织...').describe('角色，机体，舰船，组织...'),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "subject_id": zod.number(),
  "subject_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "subject_name": zod.string(),
  "subject_name_cn": zod.string(),
  "staff": zod.string().optional()
})
export const getRelatedCharactersByPersonIdResponse = zod.array(getRelatedCharactersByPersonIdResponseItem)


/**
 * 为当前用户收藏人物
 * @summary Collect person for current user
 */
export const collectPersonByPersonIdAndUserIdParams = zod.object({
  "person_id": zod.number().min(1).describe('人物 ID')
})


/**
 * 为当前用户取消收藏人物
 * @summary Uncollect person for current user
 */
export const uncollectPersonByPersonIdAndUserIdParams = zod.object({
  "person_id": zod.number().min(1).describe('人物 ID')
})


/**
 * 获取用户信息
 * @summary Get User by name
 */
export const getUserByNameParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。')
})

export const getUserByNameResponse = zod.object({
  "id": zod.number(),
  "username": zod.string().describe('唯一用户名，初始与 UID 相同，可修改一次'),
  "nickname": zod.string(),
  "user_group": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5),zod.literal(8),zod.literal(9),zod.literal(10),zod.literal(11)]).describe('用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户 - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人'),
  "avatar": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string()
}),
  "sign": zod.string().describe('个人签名')
}).describe('实际的返回值可能包括文档未声明的 `url` 字段，此字段主要用于开发者从 api 响应直接转跳到网页。\n客户端开发者请不用依赖于此特性，此字段的值随时可能会改变。\n')


/**
 * 获取用户头像，302 重定向至头像地址，设置了 username 之后无法使用 UID 查询。
 * @summary Get User Avatar by name
 */
export const getUserAvatarByNameParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。')
})

export const getUserAvatarByNameQueryParams = zod.object({
  "type": zod.string().describe('枚举值 {small|large|medium}')
})


/**
 * 返回当前 Access Token 对应的用户信息
 * @summary Get User
 */
export const getMyselfResponse = zod.object({
  "id": zod.number(),
  "username": zod.string().describe('唯一用户名，初始与 UID 相同，可修改一次'),
  "nickname": zod.string(),
  "user_group": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5),zod.literal(8),zod.literal(9),zod.literal(10),zod.literal(11)]).describe('用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户 - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人'),
  "avatar": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string()
}),
  "sign": zod.string().describe('个人签名')
}).describe('实际的返回值可能包括文档未声明的 `url` 字段，此字段主要用于开发者从 api 响应直接转跳到网页。\n客户端开发者请不用依赖于此特性，此字段的值随时可能会改变。\n').and(zod.any()).and(zod.object({
  "email": zod.string().email().optional().describe('用户绑定的邮箱地址'),
  "reg_time": zod.string().datetime({}).optional().describe('用户注册时间。比如 2017-12-03T08:51:16+08:00'),
  "time_offset": zod.number().optional().describe('用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8')
}))


/**
 * 获取对应用户的收藏，查看私有收藏需要access token。
 * @summary 获取用户收藏
 */
export const getUserCollectionsByUsernameParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。')
})

export const getUserCollectionsByUsernameQueryLimitDefault = 30;
export const getUserCollectionsByUsernameQueryLimitMax = 50;
export const getUserCollectionsByUsernameQueryOffsetDefault = 0;
export const getUserCollectionsByUsernameQueryOffsetMin = 0;


export const getUserCollectionsByUsernameQueryParams = zod.object({
  "subject_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).optional().describe('条目类型，默认为全部\n\n具体含义见 [SubjectType](#model-SubjectType)'),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5)]).describe('- `1`: 想看\n- `2`: 看过\n- `3`: 在看\n- `4`: 搁置\n- `5`: 抛弃').optional().describe('收藏类型，默认为全部\n\n具体含义见 [CollectionType](#model-CollectionType)'),
  "limit": zod.number().min(1).max(getUserCollectionsByUsernameQueryLimitMax).default(getUserCollectionsByUsernameQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getUserCollectionsByUsernameQueryOffsetMin).optional().describe('分页参数')
})

export const getUserCollectionsByUsernameResponseTotalDefault = 0;export const getUserCollectionsByUsernameResponseLimitDefault = 0;export const getUserCollectionsByUsernameResponseOffsetDefault = 0;export const getUserCollectionsByUsernameResponseDataDefault = [];

export const getUserCollectionsByUsernameResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "subject_id": zod.number(),
  "subject_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "rate": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5)]).describe('- `1`: 想看\n- `2`: 看过\n- `3`: 在看\n- `4`: 搁置\n- `5`: 抛弃'),
  "comment": zod.string().optional(),
  "tags": zod.array(zod.string()),
  "ep_status": zod.number(),
  "vol_status": zod.number(),
  "updated_at": zod.string().datetime({}).describe('本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性'),
  "private": zod.boolean(),
  "subject": zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "short_summary": zod.string().describe('截短后的条目描述。'),
  "date": zod.string().optional().describe('air date in `YYYY-MM-DD` format'),
  "images": zod.object({
  "large": zod.string(),
  "common": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}),
  "volumes": zod.number().describe('书籍条目的册数，由旧服务端从wiki中解析'),
  "eps": zod.number().describe('由旧服务端从wiki中解析，对于书籍条目为`话数`'),
  "collection_total": zod.number().describe('收藏人数'),
  "score": zod.number().describe('分数'),
  "rank": zod.number().describe('排名'),
  "tags": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
})).describe('前 10 个 tag')
}).optional()
})).default(getUserCollectionsByUsernameResponseDataDefault)
})


/**
 * 获取对应用户的收藏，查看私有收藏需要 access token
 * @summary 获取用户单个条目收藏
 */
export const getUserCollectionParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。'),
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const getUserCollectionResponse = zod.object({
  "subject_id": zod.number(),
  "subject_type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "rate": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5)]).describe('- `1`: 想看\n- `2`: 看过\n- `3`: 在看\n- `4`: 搁置\n- `5`: 抛弃'),
  "comment": zod.string().optional(),
  "tags": zod.array(zod.string()),
  "ep_status": zod.number(),
  "vol_status": zod.number(),
  "updated_at": zod.string().datetime({}).describe('本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性'),
  "private": zod.boolean(),
  "subject": zod.object({
  "id": zod.number(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "short_summary": zod.string().describe('截短后的条目描述。'),
  "date": zod.string().optional().describe('air date in `YYYY-MM-DD` format'),
  "images": zod.object({
  "large": zod.string(),
  "common": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}),
  "volumes": zod.number().describe('书籍条目的册数，由旧服务端从wiki中解析'),
  "eps": zod.number().describe('由旧服务端从wiki中解析，对于书籍条目为`话数`'),
  "collection_total": zod.number().describe('收藏人数'),
  "score": zod.number().describe('分数'),
  "rank": zod.number().describe('排名'),
  "tags": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
})).describe('前 10 个 tag')
}).optional()
})


/**
 * 修改条目收藏状态, 如果不存在则创建，如果存在则修改

由于直接修改剧集条目的完成度可能会引起意料之外效果，只能用于修改书籍类条目的完成度。

方法的所有请求体字段均可选

 * @summary 新增或修改用户单个条目收藏
 */
export const postUserCollectionParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const postUserCollectionBodyRateMin = 0;

export const postUserCollectionBodyRateMax = 10;
export const postUserCollectionBodyEpStatusMin = 0;
export const postUserCollectionBodyVolStatusMin = 0;


export const postUserCollectionBody = zod.object({
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5)]).describe('- `1`: 想看\n- `2`: 看过\n- `3`: 在看\n- `4`: 搁置\n- `5`: 抛弃').optional().describe('修改条目收藏类型'),
  "rate": zod.number().min(postUserCollectionBodyRateMin).max(postUserCollectionBodyRateMax).optional().describe('评分，`0` 表示删除评分'),
  "ep_status": zod.number().min(postUserCollectionBodyEpStatusMin).optional().describe('只能用于修改书籍条目进度'),
  "vol_status": zod.number().min(postUserCollectionBodyVolStatusMin).optional().describe('只能用于修改书籍条目进度'),
  "comment": zod.string().optional().describe('评价'),
  "private": zod.boolean().optional().describe('仅自己可见'),
  "tags": zod.array(zod.string().describe('不能包含空格')).optional().describe('不传或者 `null` 都会被忽略，传 `[]` 则会删除所有 tag。')
}).describe('所有的字段均可选')


/**
 * 修改条目收藏状态

由于直接修改剧集条目的完成度可能会引起意料之外效果，只能用于修改书籍类条目的完成度。

PATCH 方法的所有请求体字段均可选

 * @summary 修改用户单个收藏
 */
export const patchUserCollectionParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const patchUserCollectionBodyRateMin = 0;

export const patchUserCollectionBodyRateMax = 10;
export const patchUserCollectionBodyEpStatusMin = 0;
export const patchUserCollectionBodyVolStatusMin = 0;


export const patchUserCollectionBody = zod.object({
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5)]).describe('- `1`: 想看\n- `2`: 看过\n- `3`: 在看\n- `4`: 搁置\n- `5`: 抛弃').optional().describe('修改条目收藏类型'),
  "rate": zod.number().min(patchUserCollectionBodyRateMin).max(patchUserCollectionBodyRateMax).optional().describe('评分，`0` 表示删除评分'),
  "ep_status": zod.number().min(patchUserCollectionBodyEpStatusMin).optional().describe('只能用于修改书籍条目进度'),
  "vol_status": zod.number().min(patchUserCollectionBodyVolStatusMin).optional().describe('只能用于修改书籍条目进度'),
  "comment": zod.string().optional().describe('评价'),
  "private": zod.boolean().optional().describe('仅自己可见'),
  "tags": zod.array(zod.string().describe('不能包含空格')).optional().describe('不传或者 `null` 都会被忽略，传 `[]` 则会删除所有 tag。')
}).describe('所有的字段均可选')


/**
 * @summary 章节收藏信息
 */
export const getUserSubjectEpisodeCollectionParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const getUserSubjectEpisodeCollectionQueryOffsetDefault = 0;
export const getUserSubjectEpisodeCollectionQueryOffsetMin = 0;
export const getUserSubjectEpisodeCollectionQueryLimitDefault = 100;
export const getUserSubjectEpisodeCollectionQueryLimitMax = 1000;


export const getUserSubjectEpisodeCollectionQueryParams = zod.object({
  "offset": zod.number().min(getUserSubjectEpisodeCollectionQueryOffsetMin).optional().describe('分页参数'),
  "limit": zod.number().min(1).max(getUserSubjectEpisodeCollectionQueryLimitMax).default(getUserSubjectEpisodeCollectionQueryLimitDefault).describe('分页参数'),
  "episode_type": zod.union([zod.literal(0),zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5),zod.literal(6)]).optional().describe('章节类型，不传则不按照章节进行筛选')
})

export const getUserSubjectEpisodeCollectionResponse = zod.object({
  "total": zod.number(),
  "limit": zod.number(),
  "offset": zod.number()
}).and(zod.object({
  "data": zod.array(zod.object({
  "episode": zod.object({
  "id": zod.number(),
  "type": zod.number().describe('`0` 本篇，`1` SP，`2` OP，`3` ED'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "sort": zod.number().describe('同类条目的排序和集数'),
  "ep": zod.number().optional().describe('条目内的集数, 从`1`开始。非本篇剧集的此字段无意义'),
  "airdate": zod.string(),
  "comment": zod.number(),
  "duration": zod.string().describe('维基人填写的原始时长'),
  "desc": zod.string().describe('简介'),
  "disc": zod.number().describe('音乐曲目的碟片数'),
  "duration_seconds": zod.number().optional().describe('服务器解析的时长，无法解析时为 `0`')
}),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('- `0`: 未收藏\n- `1`: 想看\n- `2`: 看过\n- `3`: 抛弃'),
  "updated_at": zod.number().describe('A int64 unix timestamp, `0` as unknown or un-recorded.')
})).optional()
}))


/**
 * 同时会重新计算条目的完成度

 * @summary 章节收藏信息
 */
export const patchUserSubjectEpisodeCollectionParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const patchUserSubjectEpisodeCollectionBody = zod.object({
  "episode_id": zod.array(zod.number()),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('- `0`: 未收藏\n- `1`: 想看\n- `2`: 看过\n- `3`: 抛弃')
})


/**
 * @summary 章节收藏信息
 */
export const getUserEpisodeCollectionParams = zod.object({
  "episode_id": zod.number().min(1).describe('章节 ID')
})

export const getUserEpisodeCollectionResponse = zod.object({
  "episode": zod.object({
  "id": zod.number(),
  "type": zod.number().describe('`0` 本篇，`1` SP，`2` OP，`3` ED'),
  "name": zod.string(),
  "name_cn": zod.string(),
  "sort": zod.number().describe('同类条目的排序和集数'),
  "ep": zod.number().optional().describe('条目内的集数, 从`1`开始。非本篇剧集的此字段无意义'),
  "airdate": zod.string(),
  "comment": zod.number(),
  "duration": zod.string().describe('维基人填写的原始时长'),
  "desc": zod.string().describe('简介'),
  "disc": zod.number().describe('音乐曲目的碟片数'),
  "duration_seconds": zod.number().optional().describe('服务器解析的时长，无法解析时为 `0`')
}),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('- `0`: 未收藏\n- `1`: 想看\n- `2`: 看过\n- `3`: 抛弃'),
  "updated_at": zod.number().describe('A int64 unix timestamp, `0` as unknown or un-recorded.')
})


/**
 * @summary 更新章节收藏信息
 */
export const putUserEpisodeCollectionParams = zod.object({
  "episode_id": zod.number().min(1).describe('章节 ID')
})

export const putUserEpisodeCollectionBody = zod.object({
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('- `0`: 未收藏\n- `1`: 想看\n- `2`: 看过\n- `3`: 抛弃')
})


/**
 * @summary 获取用户角色收藏列表
 */
export const getUserCharacterCollectionsParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。')
})

export const getUserCharacterCollectionsResponseTotalDefault = 0;export const getUserCharacterCollectionsResponseLimitDefault = 0;export const getUserCharacterCollectionsResponseOffsetDefault = 0;export const getUserCharacterCollectionsResponseDataDefault = [];

export const getUserCharacterCollectionsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('type of a character 角色，机体，舰船，组织...').describe('角色，机体，舰船，组织...'),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "created_at": zod.string().datetime({})
})).default(getUserCharacterCollectionsResponseDataDefault)
})


/**
 * @summary 获取用户单个角色收藏信息
 */
export const getUserCharacterCollectionParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。'),
  "character_id": zod.number().min(1).describe('角色 ID')
})

export const getUserCharacterCollectionResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4)]).describe('type of a character 角色，机体，舰船，组织...').describe('角色，机体，舰船，组织...'),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "created_at": zod.string().datetime({})
})


/**
 * @summary 获取用户人物收藏列表
 */
export const getUserPersonCollectionsParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。')
})

export const getUserPersonCollectionsResponseTotalDefault = 0;export const getUserPersonCollectionsResponseLimitDefault = 0;export const getUserPersonCollectionsResponseOffsetDefault = 0;export const getUserPersonCollectionsResponseDataDefault = [];

export const getUserPersonCollectionsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`').describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`'),
  "career": zod.array(zod.enum(['producer', 'mangaka', 'artist', 'seiyu', 'writer', 'illustrator', 'actor']).describe('An enumeration.')),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "created_at": zod.string().datetime({})
})).default(getUserPersonCollectionsResponseDataDefault)
})


/**
 * @summary 获取用户单个人物收藏信息
 */
export const getUserPersonCollectionParams = zod.object({
  "username": zod.string().describe('设置了用户名之后无法使用 UID。'),
  "person_id": zod.number().min(1).describe('人物 ID')
})

export const getUserPersonCollectionResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3)]).describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`').describe('`1`, `2`, `3` 表示 `个人`, `公司`, `组合`'),
  "career": zod.array(zod.enum(['producer', 'mangaka', 'artist', 'seiyu', 'writer', 'illustrator', 'actor']).describe('An enumeration.')),
  "images": zod.object({
  "large": zod.string(),
  "medium": zod.string(),
  "small": zod.string(),
  "grid": zod.string()
}).optional().describe('object with some size of images, this object maybe `null`'),
  "created_at": zod.string().datetime({})
})


/**
 * @summary Get Person Revisions
 */
export const getPersonRevisionsQueryLimitDefault = 30;
export const getPersonRevisionsQueryLimitMax = 50;
export const getPersonRevisionsQueryOffsetDefault = 0;
export const getPersonRevisionsQueryOffsetMin = 0;


export const getPersonRevisionsQueryParams = zod.object({
  "person_id": zod.number().min(1).describe('角色 ID'),
  "limit": zod.number().min(1).max(getPersonRevisionsQueryLimitMax).default(getPersonRevisionsQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getPersonRevisionsQueryOffsetMin).optional().describe('分页参数')
})

export const getPersonRevisionsResponseTotalDefault = 0;export const getPersonRevisionsResponseLimitDefault = 0;export const getPersonRevisionsResponseOffsetDefault = 0;export const getPersonRevisionsResponseDataDefault = [];

export const getPersonRevisionsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({})
})).default(getPersonRevisionsResponseDataDefault)
})


/**
 * @summary Get Person Revision
 */
export const getPersonRevisionByRevisionIdParams = zod.object({
  "revision_id": zod.number().min(1).describe('历史版本 ID')
})

export const getPersonRevisionByRevisionIdResponse = zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({})
}).and(zod.object({
  "data": zod.record(zod.string(), zod.object({
  "prsn_infobox": zod.string(),
  "prsn_summary": zod.string(),
  "profession": zod.object({
  "producer": zod.string().optional(),
  "mangaka": zod.string().optional(),
  "artist": zod.string().optional(),
  "seiyu": zod.string().optional(),
  "writer": zod.string().optional(),
  "illustrator": zod.string().optional(),
  "actor": zod.string().optional()
}),
  "extra": zod.object({
  "img": zod.string().optional()
}),
  "prsn_name": zod.string()
})).optional()
}))


/**
 * @summary Get Character Revisions
 */
export const getCharacterRevisionsQueryLimitDefault = 30;
export const getCharacterRevisionsQueryLimitMax = 50;
export const getCharacterRevisionsQueryOffsetDefault = 0;
export const getCharacterRevisionsQueryOffsetMin = 0;


export const getCharacterRevisionsQueryParams = zod.object({
  "character_id": zod.number().min(1).describe('角色 ID'),
  "limit": zod.number().min(1).max(getCharacterRevisionsQueryLimitMax).default(getCharacterRevisionsQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getCharacterRevisionsQueryOffsetMin).optional().describe('分页参数')
})

export const getCharacterRevisionsResponseTotalDefault = 0;export const getCharacterRevisionsResponseLimitDefault = 0;export const getCharacterRevisionsResponseOffsetDefault = 0;export const getCharacterRevisionsResponseDataDefault = [];

export const getCharacterRevisionsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({})
})).default(getCharacterRevisionsResponseDataDefault)
})


/**
 * @summary Get Character Revision
 */
export const getCharacterRevisionByRevisionIdParams = zod.object({
  "revision_id": zod.number().min(1).describe('版本 ID')
})

export const getCharacterRevisionByRevisionIdResponse = zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({})
}).and(zod.object({
  "data": zod.record(zod.string(), zod.object({
  "infobox": zod.string(),
  "summary": zod.string(),
  "name": zod.string(),
  "extra": zod.object({
  "img": zod.string().optional()
})
})).optional()
}))


/**
 * @summary Get Subject Revisions
 */
export const getSubjectRevisionsQueryLimitDefault = 30;
export const getSubjectRevisionsQueryLimitMax = 50;
export const getSubjectRevisionsQueryOffsetDefault = 0;
export const getSubjectRevisionsQueryOffsetMin = 0;


export const getSubjectRevisionsQueryParams = zod.object({
  "subject_id": zod.number().min(1).describe('条目 ID'),
  "limit": zod.number().min(1).max(getSubjectRevisionsQueryLimitMax).default(getSubjectRevisionsQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getSubjectRevisionsQueryOffsetMin).optional().describe('分页参数')
})

export const getSubjectRevisionsResponseTotalDefault = 0;export const getSubjectRevisionsResponseLimitDefault = 0;export const getSubjectRevisionsResponseOffsetDefault = 0;export const getSubjectRevisionsResponseDataDefault = [];

export const getSubjectRevisionsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({})
})).default(getSubjectRevisionsResponseDataDefault)
})


/**
 * @summary Get Subject Revision
 */
export const getSubjectRevisionByRevisionIdParams = zod.object({
  "revision_id": zod.number().min(1).describe('版本 ID')
})

export const getSubjectRevisionByRevisionIdResponse = zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({})
}).and(zod.object({
  "data": zod.object({
  "field_eps": zod.number(),
  "field_infobox": zod.string(),
  "field_summary": zod.string(),
  "name": zod.string(),
  "name_cn": zod.string(),
  "platform": zod.number(),
  "subject_id": zod.number(),
  "type": zod.number(),
  "type_id": zod.number(),
  "vote_field": zod.string()
}).optional()
}))


/**
 * @summary Get Episode Revisions
 */
export const getEpisodeRevisionsQueryLimitDefault = 30;
export const getEpisodeRevisionsQueryLimitMax = 50;
export const getEpisodeRevisionsQueryOffsetDefault = 0;
export const getEpisodeRevisionsQueryOffsetMin = 0;


export const getEpisodeRevisionsQueryParams = zod.object({
  "episode_id": zod.number().min(1).describe('章节 ID'),
  "limit": zod.number().min(1).max(getEpisodeRevisionsQueryLimitMax).default(getEpisodeRevisionsQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getEpisodeRevisionsQueryOffsetMin).optional().describe('分页参数')
})

export const getEpisodeRevisionsResponseTotalDefault = 0;export const getEpisodeRevisionsResponseLimitDefault = 0;export const getEpisodeRevisionsResponseOffsetDefault = 0;export const getEpisodeRevisionsResponseDataDefault = [];

export const getEpisodeRevisionsResponse = zod.object({
  "total": zod.number().optional(),
  "limit": zod.number().optional(),
  "offset": zod.number().optional(),
  "data": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({})
})).default(getEpisodeRevisionsResponseDataDefault)
})


/**
 * @summary Get Episode Revision
 */
export const getEpisodeRevisionByRevisionIdParams = zod.object({
  "revision_id": zod.number().min(1).describe('版本 ID')
})

export const getEpisodeRevisionByRevisionIdResponse = zod.object({
  "id": zod.number(),
  "type": zod.number(),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).optional().describe('意义同<a href=\"#model-Me\">Me</a>'),
  "summary": zod.string(),
  "created_at": zod.string().datetime({}),
  "data": zod.object({

}).optional().describe('编辑修改内容，响应类型不固定')
})


/**
 * @summary Create a new index
 */
export const newIndexResponseTotalDefault = 0;

export const newIndexResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "desc": zod.string(),
  "total": zod.number().optional().describe('收录条目总数'),
  "stat": zod.object({
  "comments": zod.number(),
  "collects": zod.number()
}).describe('目录评论及收藏数'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).describe('意义同<a href=\"#model-Me\">Me</a>'),
  "ban": zod.boolean().describe('deprecated, always false.'),
  "nsfw": zod.boolean()
})


/**
 * @summary Get Index By ID
 */
export const getIndexByIdParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID')
})

export const getIndexByIdResponseTotalDefault = 0;

export const getIndexByIdResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "desc": zod.string(),
  "total": zod.number().optional().describe('收录条目总数'),
  "stat": zod.object({
  "comments": zod.number(),
  "collects": zod.number()
}).describe('目录评论及收藏数'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).describe('意义同<a href=\"#model-Me\">Me</a>'),
  "ban": zod.boolean().describe('deprecated, always false.'),
  "nsfw": zod.boolean()
})


/**
 * @summary Edit index's information
 */
export const editIndexByIdParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID')
})

export const editIndexByIdBody = zod.object({
  "title": zod.string().optional(),
  "description": zod.string().optional()
}).describe('新增或修改条目的内容，同名字段意义同<a href=\"#model-Subject\">Subject</a>')

export const editIndexByIdResponseTotalDefault = 0;

export const editIndexByIdResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "desc": zod.string(),
  "total": zod.number().optional().describe('收录条目总数'),
  "stat": zod.object({
  "comments": zod.number(),
  "collects": zod.number()
}).describe('目录评论及收藏数'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "creator": zod.object({
  "username": zod.string(),
  "nickname": zod.string()
}).describe('意义同<a href=\"#model-Me\">Me</a>'),
  "ban": zod.boolean().describe('deprecated, always false.'),
  "nsfw": zod.boolean()
})


/**
 * @summary Get Index Subjects
 */
export const getIndexSubjectsByIndexIdParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID')
})

export const getIndexSubjectsByIndexIdQueryLimitDefault = 30;
export const getIndexSubjectsByIndexIdQueryLimitMax = 50;
export const getIndexSubjectsByIndexIdQueryOffsetDefault = 0;
export const getIndexSubjectsByIndexIdQueryOffsetMin = 0;


export const getIndexSubjectsByIndexIdQueryParams = zod.object({
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).optional().describe('条目类型'),
  "limit": zod.number().min(1).max(getIndexSubjectsByIndexIdQueryLimitMax).default(getIndexSubjectsByIndexIdQueryLimitDefault).describe('分页参数'),
  "offset": zod.number().min(getIndexSubjectsByIndexIdQueryOffsetMin).optional().describe('分页参数')
})


/**
 * @summary Add a subject to Index
 */
export const addSubjectToIndexByIndexIdParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID')
})

export const addSubjectToIndexByIndexIdBody = zod.object({
  "subject_id": zod.number().optional(),
  "sort": zod.number().optional().describe('排序条件，越小越靠前'),
  "comment": zod.string().optional()
}).describe('新增某条目到目录的请求信息')


/**
 * 如果条目不存在于目录，会创建该条目
 * @summary Edit subject information in a index
 */
export const editIndexSubjectsByIndexIdAndSubjectIDParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID'),
  "subject_id": zod.number().min(1).describe('条目 ID')
})

export const editIndexSubjectsByIndexIdAndSubjectIDBody = zod.object({
  "sort": zod.number().optional().describe('排序条件，越小越靠前'),
  "comment": zod.string().optional()
}).describe('修改目录中条目的信息')


/**
 * @summary Delete a subject from a Index
 */
export const delelteSubjectFromIndexByIndexIdAndSubjectIDParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID'),
  "subject_id": zod.number().min(1).describe('条目 ID')
})


/**
 * 为当前用户收藏一条目录
 * @summary Collect index for current user
 */
export const collectIndexByIndexIdAndUserIdParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID')
})


/**
 * 为当前用户取消收藏一条目录
 * @summary Uncollect index for current user
 */
export const uncollectIndexByIndexIdAndUserIdParams = zod.object({
  "index_id": zod.number().min(1).describe('目录 ID')
})
