/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token

## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)

如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。

 * OpenAPI spec version: dev
 */
import {
  z as zod
} from 'zod';

/**
 * @summary 每日放送
 */
export const getCalendarResponseItem = zod.object({
  "weekday": zod.object({
  "en": zod.string().optional(),
  "cn": zod.string().optional(),
  "ja": zod.string().optional(),
  "id": zod.number().optional()
}).optional(),
  "items": zod.array(zod.object({
  "id": zod.number().optional().describe('条目 ID'),
  "url": zod.string().optional().describe('条目地址'),
  "type": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(6)]).optional().describe('条目类型\n- `1` 为 书籍\n- `2` 为 动画\n- `3` 为 音乐\n- `4` 为 游戏\n- `6` 为 三次元\n\n没有 `5`'),
  "name": zod.string().optional().describe('条目名称'),
  "name_cn": zod.string().optional().describe('条目中文名称'),
  "summary": zod.string().optional().describe('剧情简介'),
  "air_date": zod.string().optional().describe('放送开始日期'),
  "air_weekday": zod.number().optional().describe('放送星期'),
  "images": zod.object({
  "large": zod.string().optional(),
  "common": zod.string().optional(),
  "medium": zod.string().optional(),
  "small": zod.string().optional(),
  "grid": zod.string().optional()
}).optional().describe('封面'),
  "eps": zod.number().optional().describe('话数'),
  "eps_count": zod.number().optional().describe('话数'),
  "rating": zod.object({
  "total": zod.number().optional().describe('总评分人数'),
  "count": zod.object({
  "1": zod.number().optional(),
  "2": zod.number().optional(),
  "3": zod.number().optional(),
  "4": zod.number().optional(),
  "5": zod.number().optional(),
  "6": zod.number().optional(),
  "7": zod.number().optional(),
  "8": zod.number().optional(),
  "9": zod.number().optional(),
  "10": zod.number().optional()
}).optional().describe('各分值评分人数'),
  "score": zod.number().optional().describe('评分')
}).optional().describe('评分'),
  "rank": zod.number().optional().describe('排名'),
  "collection": zod.object({
  "wish": zod.number().optional().describe('想做'),
  "collect": zod.number().optional().describe('做过'),
  "doing": zod.number().optional().describe('在做'),
  "on_hold": zod.number().optional().describe('搁置'),
  "dropped": zod.number().optional().describe('抛弃')
}).optional().describe('收藏人数')
})).optional()
})
export const getCalendarResponse = zod.array(getCalendarResponseItem)
